version: '3'

services:
  nginx:
    build: .docker/nginx
    container_name: turistando_nginx
    tty: true
    ports:
      - "80:80"
    volumes:
      - .:/var/www
    networks:
      - turistando_app_networks
    depends_on:
      - app

  app:
    build: .
    container_name: turistando_app
    entrypoint: dockerize
      -template ./.docker/app/.env:.env
      -wait tcp://db:3306
      -timeout 40s
      ./.docker/entrypoint.sh
    environment:
      - _DB_HOST=turistando_db
      - _DB_DATABASE=turistando
      - _DB_USERNAME=root
      - _DB_PASSWORD=X7vbCnT2ZUkURZv6vkq
      - TEST_DB_DATABASE=turistando_test
      - _REDIS_HOST=redis
    volumes:
      - .:/var/www
    networks:
      - turistando_app_networks
    depends_on:
      - db
      - redis

  redis:
    image: redis:alpine
    container_name: turistando_redis
    expose:
      - 6379
    networks:
      - turistando_app_networks

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: turistando_db
    tty: true
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=turistando
      - MYSQL_USER=turistando_user
      - MYSQL_ROOT_PASSWORD=X7vbCnT2ZUkURZv6vkq
      - MYSQL_PASSWORD=X7vbCnT2ZUkURZv6vkq
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
      - ./.docker/mysql:/docker-entrypoint-initdb.d
    networks:
      - turistando_app_networks

networks:
  turistando_app_networks:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.18.3.0/24"
